# Generated by Django 5.0.1 on 2024-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('post', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=155)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=155, verbose_name='Sarlavha')),
                ('description1', models.TextField(verbose_name='Text 1')),
                ('description2', models.TextField(verbose_name='Text 2')),
                ('paragraph', models.CharField(max_length=155, verbose_name='Mavzu')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
