# Generated by Django 5.0.1 on 2024-01-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
