# Generated by Django 5.0.1 on 2024-01-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_full_name_comment_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='first_name',
            new_name='username',
        ),
    ]
